input_dir: /scratch/data/TopPhysics/mvaDirs/inputs/2016/all/mz20mw20/
seed: 52
selection: >-
    chi2 < 40 &&
    Channel == 1
negative_weight_treatment: passthrough
signals:
    - tZq
backgrounds:
    - DYToLL_M10To50_aMCatNLO
    - DYToLL_M50_aMCatNLO
    - FakeEG
    - FakeMu
    - TbartChan
    - TbartW
    - THQ
    - TsChan
    - TT
    - TtChan
    - ttH
    - TTW
    - TtW
    - TTZ
    - TWZ
    - Wjets
    - WW
    - WWW
    - WWZ
    - WZ
    - WZZ
    - ZZ
    - ZZZ
data_process: DataEG
equalise_signal: true
channel: ee
plot_dir: plots2D/
root_dir: root2D/
mva_dir: mva2D/

classifier1: mva1/mlp_ee.pkl
classifier2: mva2/mlp_ee.pkl

# How the results of the two classifiers should be combined
#   min: minimum response
#   max: maximum response
#   add: sum of the responses
#   quadrature: sum of the responses in quadrature
#   PCA: Use Principal Component Analysis to project the responses to 1D
#   kmeans: Use kmeans to cluster the results, sort clusters by S/N ratio,
#           and create bins in numeric cluster labels
combination: recursive_kmeans

root_out:
    combine: true
    drop_nan: true
    data: empty
    bins: 200
    min_signal_events: 0
    min_background_events: 1
    max_signal_error: 0.3
    max_background_error: 0.3
