input_dir: /scratch/data/TopPhysics/mvaDirs/inputs/2016/all/mz20mw20/
seed: 52
selection: >-
    chi2 < 40 &&
    Channel == 1
channel: ee
signals:
    - tZq
backgrounds:
    - TbartChan
    - TbartW
    - THQ
    - TsChan
    - TT
    - TtChan
    - ttH
    - TTW
    - TtW
    - Wjets
    - WW
    - WWW
data_process: DataEG
plot_dir: plots2/
root_dir: root2/
mva_dir: mva2/
test_fraction: 0.33
equalise_signal: true
negative_weight_treatment: reweight
preprocessors:
    - preprocessor: robust_scaler
      config: {}
classifier: mlp
mlp:
    model:
        backend: theano
        class_name: Sequential
        config:
        - class_name: Dense
          config:
            activation: tanh
            # activity_regularizer:
            #   class_name: L1L2
            #   config: {l1: 0.0, l2: 0.0}
            # kernel_regularizer:
            #   class_name: L1L2
            #   config: {l1: 0, l2: 1e-4}
            # bias_regularizer:
            #   class_name: L1L2
            #   config: {l1: 0, l2: 1e-3}
            units: 32
        - class_name: Dense
          config:
            activation: sigmoid
            units: 1
    model_params:
        epochs: 10000
        verbose: 1
        batch_size: 256
    compile_params:
        loss: binary_crossentropy
        optimizer: adam
        metrics:
            - accuracy
    lr_reduction_params:
        monitor: loss
        factor: 0.1
        patience: 2
        verbose: 1
    early_stopping_params:
        monitor: loss
        min_delta: 0
        patience: 10
        verbose: 0
        mode: auto
root_out:
    combine: true
    drop_nan: true
    data: empty
    bins: 200
features:
    # - bTagDisc
    # - fourthJetEta
    # - fourthJetPhi
    # - fourthJetPt
    # - fourthJetbTag
    # - jetHt
    # - jetMass
    - jetMass3
    # - jjdelPhi
    - jjdelR
    # - leadJetEta
    # - leadJetPhi
    # - leadJetPt
    # - leadJetbTag
    # - lep1D0
    # - lep1Eta
    # - lep1Phi
    # - lep1Pt
    # - lep1RelIso
    # - lep2D0
    # - lep2Eta
    # - lep2Phi
    # - lep2Pt
    # - lep2RelIso
    - lepEta
    # - lepHt
    # - mTW
    - met
    - nBjets
    # - nJets
    # - secJetEta
    # - secJetPhi
    # - secJetPt
    # - secJetbTag
    # - thirdJetEta
    # - thirdJetPhi
    # - thirdJetPt
    # - thirdJetbTag
    # - topEta
    - topMass
    # - topPhi
    # - topPt
    # - totEta
    - totHt
    - totHtOverPt
    # - totPt
    # - totPt2Jet
    # - totPtVec
    # - totVecM
    # - w1TopDelPhi
    # - w1TopDelR
    # - w2TopDelPhi
    # - w2TopDelR
    # - wPairEta
    # - wPairMass
    # - wPairPhi
    # - wPairPt
    # - wQuark1Eta
    # - wQuark1Phi
    # - wQuark1Pt
    # - wQuark2Eta
    # - wQuark2Phi
    # - wQuark2Pt
    # - wQuarkHt
    # - wTopDelPhi
    # - wTopDelR
    # - wwdelPhi
    # - wwdelR
    # - wzdelPhi
    # - wzdelR
    # - zEta
    # - zLepdelPhi
    # - zLepdelR
    - zMass
    # - zPhi
    - zPt
    # - zQuark1DelPhi
    # - zQuark1DelR
    # - zQuark2DelPhi
    # - zQuark2DelR
    # - zTopDelPhi
    - zTopDelR
    # - zjminPhi
    - zjminR
    # - zl1Quark1DelPhi
    # - zl1Quark1DelR
    # - zl1Quark2DelPhi
    # - zl1Quark2DelR
    # - zl1TopDelPhi
    # - zl1TopDelR
    # - zl2Quark1DelPhi
    # - zl2Quark1DelR
    # - zl2Quark2DelPhi
    # - zl2Quark2DelR
    # - zl2TopDelPhi
    # - zl2TopDelR
    # - zlb1DelPhi
    - zlb1DelR
    # - zlb2DelPhi
    - zlb2DelR
